create table if not exists public.scrape_runs (
    id uuid primary key,
    source text not null,
    category text not null,
    catalog_url text not null,
    storage_mode text not null,
    status text not null default 'running'
        check (status in ('running', 'completed', 'partial', 'failed', 'cancelled')),
    full_scan boolean not null default false,
    products_found integer not null default 0 check (products_found >= 0),
    products_saved integer not null default 0 check (products_saved >= 0),
    products_failed integer not null default 0 check (products_failed >= 0),
    error_message text,
    started_at timestamptz not null default now(),
    finished_at timestamptz
);

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    source text not null default 'vistasport',
    category text not null default 'blades',
    source_url text not null unique,
    name text not null,
    brand text,
    description text not null default '',
    price numeric(12, 2) check (price is null or price >= 0),
    currency text check (currency is null or char_length(currency) = 3),
    available boolean not null default false,
    characteristics jsonb not null default '{}'::jsonb,
    image_url text,
    content_hash char(64) not null,
    last_seen_run_id uuid references public.scrape_runs(id),
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
    id bigint generated by default as identity primary key,
    product_id bigint not null references public.products(id) on delete cascade,
    source_key text not null,
    sku text,
    name text not null,
    price numeric(12, 2) check (price is null or price >= 0),
    currency text check (currency is null or char_length(currency) = 3),
    available boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (product_id, source_key)
);

create index if not exists products_available_idx
    on public.products (available);
create index if not exists products_brand_idx
    on public.products (brand);
create index if not exists products_last_seen_run_idx
    on public.products (last_seen_run_id);
create index if not exists product_variants_product_idx
    on public.product_variants (product_id);

alter table public.scrape_runs enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
